### ISSUE TITLE
the servictier does not have enough time to start

### ISSUE THREAD

**Issue by Hmeyer-Simova** [lippertmarkus/helm-charts#1]
you have three probes in your deployment.yaml that prevent business central(tested with 17-0) from starting. best take out the lines or extend the time.

With kind regards

**Comment by lippertmarkus** [comment]
Hey @Hmeyer-Simova,

I just tried with BC 17.0 and hadn't had any problem. 

`config.yml`:
```yaml
service:
  type: LoadBalancer

image:
  repository: mcr.microsoft.com/dynamicsnav
  tag: "10.0.17763.1397-generic"
  artifactUrl: "https://bcartifacts.azureedge.net/onprem/17.0.16993.0/w1"

env:
  ACCEPT_OUTDATED: "Y"
```

The Pod events show that the startup probe failed 55 times, but the startup probe allows 70 failures, so there should be still room left:
```
Events:
 Type     Reason     Age                     From               Message
 ----     ------     ----                    ----               -------
 Normal   Scheduled  8m23s                   default-scheduler  Successfully assigned default/bc1-business-central-7f777d85d8-flhlg to akswin000000
 Normal   Pulled     8m20s                   kubelet            Container image "mcr.microsoft.com/dynamicsnav:10.0.17763.1397-generic" already present on machine
 Normal   Created    8m20s                   kubelet            Created container business-central
 Normal   Started    8m19s                   kubelet            Started container business-central
 Warning  Unhealthy  3m17s (x55 over 7m45s)  kubelet            Startup probe failed:   
```

Sure that depends on the performance of your network and the worker machines. 

Could you check if that's really the problem? If that's the case I could make that configurable for you.
