### ISSUE TITLE
Stuck at "Starting Business Central Tier"

### ISSUE THREAD

**Issue by eokorieFA** [lippertmarkus/helm-charts#5]
Hi,

Hope you can help.  I am currently attempting to deploy Business Central to Kubernetes cluster using Helm and Terraform.  I am sure I have configured the helm file correctly as checking the logs I can see the Helm setting up the application.  However, when it gets to "Starting Business Central Tier" , the application just stays stuck there and the installation process being again.  I have a timeout of 15 mins in place to make sure that the intall process does not run unncessarily for too long.

Below is a log from the pod:

```
Adding BUSINESS-CENTRA to hosts file
Using artifactUrl https://bcartifacts.azureedge.net/onprem/16.5.15897.15953/w1
Downloading application artifact /onprem/16.5.15897.15953/w1
Downloading C:\Users\ContainerAdministrator\AppData\Local\Temp\4cdca395-c301-4ba2-a40c-369c3c8ed8ec.zip
Unpacking application artifact
Downloading platform artifact /onprem/16.5.15897.15953/platform
Downloading C:\Users\ContainerAdministrator\AppData\Local\Temp\4a4cd2df-0c98-4eca-b346-162334e37017.zip
Unpacking platform artifact
Downloading Prerequisite Components
Downloading c:\dl\onprem\16.5.15897.15953\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Downloading c:\dl\onprem\16.5.15897.15953\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\dl\onprem\16.5.15897.15953\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\16.5.15897.15953\platform\ServiceTier\Program Files
c:\dl\onprem\16.5.15897.15953\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\16.5.15897.15953\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\16.5.15897.15953\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\16.5.15897.15953\w1\database\Demo Database NAV (16-0).bak
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\onprem\16.5.15897.15953\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\onprem\16.5.15897.15953\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\16.5.15897.15953\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\16.5.15897.15953\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\onprem\16.5.15897.15953\platform
c:\dl\onprem\16.5.15897.15953\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\16.5.15897.15953\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\16.5.15897.15953\platform\Test Assemblies
Copying Applications
C:\dl\onprem\16.5.15897.15953\platform\Applications
Starting Business Central Service Tier

```

Terraform Helm release:
```
resource "kubernetes_namespace" "business_central" {
  metadata {
    name = "business-central"
  }
}

resource "helm_release" "business_central" {
  name          = "business-central"
  repository    = "https://charts.lippertmarkus.com"
  chart         = "business-central"
  namespace     = kubernetes_namespace.business_central.metadata.0.name

  timeout = 900 // 15 mins wait timeout

  values = [file("configurations/business_central/values.yaml")]

//  depends_on = [
//      helm_release.ingress
//  ]
}
```

This is the yaml file I am using for the deployment of the application
```
probes:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
  path: /bc/(/|$)(.*)
  hosts:
    - host: bcentral-dev.domain.io
      path: /bc(/|$)(.*)
      serviceport: web
  tls:
    - secretName: bcentral-dev-tls
      hosts:
        - bcentral-dev.domain.io
```

Any ideas as to what may be going wrong here?  The windows node version is at AKSWindows-2019-17763.2213.210922
while the container version is docker://20.10.6

Thanks,

Emmanuel
